spring:
  data:
    mongo:
      uri: ${MONGODB_URI:mongodb+srv://products-admin:p01admin@cluster0.bpqir.mongodb.net/Products?authSource=admin&replicaSet=atlas-7f6ug8-shard-0&w=majority&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true}
